// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/service.mdx?collection=docs&hash=1767771602526"
import * as docs_6 from "../content/docs/faq.mdx?collection=docs&hash=1767771602526"
import * as docs_5 from "../content/docs/claude-window-init.mdx?collection=docs&hash=1767771602526"
import * as docs_4 from "../content/docs/claude-skill-two.mdx?collection=docs&hash=1767771602526"
import * as docs_3 from "../content/docs/claude-skill-one.mdx?collection=docs&hash=1767771602526"
import * as docs_2 from "../content/docs/claude-init.mdx?collection=docs&hash=1767771602526"
import * as docs_1 from "../content/docs/claude-cache.mdx?collection=docs&hash=1767771602526"
import * as docs_0 from "../content/docs/best-practices.mdx?collection=docs&hash=1767771602526"
import * as blogs_1 from "../content/blog/question.mdx?collection=blogs&hash=1767771602526"
import * as blogs_0 from "../content/blog/commercial.mdx?collection=blogs&hash=1767771602526"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blogs = _runtime.docs<typeof _source.blogs>([{ info: {"path":"commercial.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/blog/commercial.mdx"}, data: blogs_0 }, { info: {"path":"question.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/blog/question.mdx"}, data: blogs_1 }], [])
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"best-practices.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/best-practices.mdx"}, data: docs_0 }, { info: {"path":"claude-cache.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/claude-cache.mdx"}, data: docs_1 }, { info: {"path":"claude-init.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/claude-init.mdx"}, data: docs_2 }, { info: {"path":"claude-skill-one.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/claude-skill-one.mdx"}, data: docs_3 }, { info: {"path":"claude-skill-two.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/claude-skill-two.mdx"}, data: docs_4 }, { info: {"path":"claude-window-init.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/claude-window-init.mdx"}, data: docs_5 }, { info: {"path":"faq.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/faq.mdx"}, data: docs_6 }, { info: {"path":"service.mdx","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/service.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","absolutePath":"/Users/dujiajian/codecli-docs/content/docs/meta.json"},"data":{"pages":["--- 🏠 CodeCli 使用---","best-practices","service","faq","--- 📖 Claude Code 教程 ---","claude-init","claude-window-init","claude-cache","--- Claude Code 精华文章 ---","claude-skill-one","claude-skill-two"]}}])